# Version info
{1}{}{FOnline: Tactics v0.00.00 :D}

# Update messages
{5}{}{ПРОВЕРКА ОБНОВЛЕНИЙ}
{6}{}{Подключение к серверу}
{7}{}{Не удалось подключиться к серверу}
{8}{}{Соединение установлено}
{9}{}{Синхронизация данных}
{10}{}{Сбой подключения}
{11}{}{Не удалось прочитать/записать файл}
{12}{}{Версия клиента устарела}
{13}{}{Версия клиента устарела, обновитесь с помощью App Store}
{14}{}{Версия клиента устарела, обновитесь с помощью Google Play}
{15}{}{Исполняемый файл клиента обновлен, перезапустите игру}
{16}{}{Данные устарели, перезапустите игру}
{17}{}{Происходит запуск игры, ждите}

####################################################################################################################################
#
#		Maintenance
#
####################################################################################################################################

{1001}{}{|4291317840 Введен неверный логин.}
{1002}{}{|4291317840 Введен неверный пароль.}
{1003}{}{|4291317840 Аккаунт с таким именем уже есть - измените логин.}
{1004}{}{|4291317840 Игрок под этим логином уже в игре.}
{1005}{}{|4291317840 Неверные данные SPECIAL.}
{1006}{}{|4291317840 Регистрация пройдена успешно.}
{1007}{}{|4291317840 Идет соединение с сервером.}
{1008}{}{|4291317840 Сбой соединения! При повторениях сбоя - обратитесь к администратору сервера.}
{1009}{}{|4291317840 Неверный логин или пароль.}
{1010}{}{|4291317840 Соединение установлено, аутентификация...}
{1012}{}{|4291317840 Гексы для высадки заняты, попробуйте войти в игру немного позже.}
{1013}{}{|4291317840 Отключение по команде игрока.}
{1014}{}{|4291317840 Ошибка в имени. Возможно слишком длинное или короткое.}
{1015}{}{|4291317840 Ошибка в одном из склонений имени. Возможно слишком длинное или короткое.}
{1016}{}{|4291317840 Пол введен неверно.}
{1017}{}{|4291317840 Возраст введен неверно.}
{1018}{}{|4291317840 Не удалось подключиться к серверу игры.}
{1019}{}{|4291317840 Введены неверные данные.}
{1020}{}{|4291317840 Ошибка поиска стартовой локации, свяжитесь с администрацией сервера.}
{1021}{}{|4291317840 Ошибка поиска стартовой карты, свяжитесь с администрацией сервера.}
{1022}{}{|4291317840 Ошибка поиска стартовых координат, свяжитесь с администрацией сервера.}
{1023}{}{|4291317840 Ошибка БД, свяжитесь с администрацией сервера.}
{1024}{}{|4291317840 Неверная версия сетевого протокола, обновите клиент.}
{1025}{}{|4291317840 Ошибка в передаче данных, попробуйте еще раз.}
{1026}{}{|4291317840 Неверное сетевое сообщение.}
{1027}{}{|4291317840 Внутренняя ошибка сервера №1, сообщите о ней администрации сервера.}
{1028}{}{|4291317840 Аутентификация пройдена, загрузка карты.}
{1029}{}{|4291317840 Выберите 3 умения.}
{1030}{}{|4291317840 Имя должно быть написано с использованием одного языка.}
{1031}{}{|4291317840 Имя на 70% должно состоять из букв алфавита.}
{1032}{}{|4291317840 Пробел не может быть использован в начале или конце имени.}
{1033}{}{|4291317840 Не допускается ставить в имени два пробела подряд.}
{1034}{}{|4291317840 Ваш аккаунт заблокирован.}
{1035}{}{|4291317840 Недопустимые символы в имени.}
{1036}{}{|4291317840 Недопустимые символы в пароле.}
{1037}{}{|4291317840 Ошибка загрузки пользовательского интерфейса.}
{1038}{}{|4291317840 Ошибка выполнения стартового скрипта.}
{1039}{}{|4291317840 Выбранный язык не поддерживается. Установлен язык по умолчанию.}
{1040}{}{|4291317840 Игра может работать некорректно при разрешениях меньше 800x600 или больше 1280x1024.}
{1041}{}{|4291317840 Тук-тук, кто-нибудь есть?}
{1042}{}{|4291317840 Обнаружены частые регистрации с одного IP адреса. Попробуйте позже.}
{1043}{}{|4291317840 Ваш IP заблокирован.}
{1044}{}{|4291317840 Минимальное время игры с одного компьютера для одного аккаунта составляет 10 минут.}
{1045}{}{|4291317840 Времени осталось: @lex time@ минут.}
{1046}{}{|4291317840 Вы были забанены.}
{1047}{}{|4291317840 Бан от: @lex banby@, Продолжительность: @lex time@ часов, Комментарий: @lex reason@.}
{1048}{}{|4291317840 Ошибка скрипта, обратитесь к администрации сервера.}
{1049}{}{|4291317840 Ваш персонаж полностью умер, игра за данный аккаунт больше невозможна.}
